# Generated by Django 5.1.6 on 2025-04-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleto',
            old_name='apartamento',
            new_name='apartamentos',
        ),
    ]
