# Generated by Django 5.1.6 on 2025-04-02 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0002_rename_apartamento_boleto_apartamentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='morador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apartamento', to=settings.AUTH_USER_MODEL),
        ),
    ]
