# Generated by Django 5.1.7 on 2025-04-04 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0003_alter_apartamento_morador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='morador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartamento', to=settings.AUTH_USER_MODEL),
        ),
    ]
