# Generated by Django 5.1.7 on 2025-04-04 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0004_alter_apartamento_morador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_postagem', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
