# Generated by Django 5.1.7 on 2025-04-05 01:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0005_aviso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('origem', models.CharField(max_length=255)),
                ('data_chegada', models.DateTimeField(default=django.utils.timezone.now)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condosync.apartamento')),
            ],
        ),
    ]
