# Generated by Django 5.1.7 on 2025-04-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0007_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
