# Generated by Django 5.1.7 on 2025-04-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0010_sugestoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoceSabia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_1', models.CharField(max_length=200)),
                ('conteudo_1', models.TextField()),
                ('titulo_2', models.CharField(max_length=200)),
                ('conteudo_2', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
