# Generated by Django 5.1.7 on 2025-05-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0012_areacomum_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='horario_fim',
            new_name='horario',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='horario_inicio',
        ),
    ]
