# Generated by Django 5.2 on 2025-05-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0013_rename_horario_fim_reserva_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='area',
        ),
        migrations.AddField(
            model_name='reserva',
            name='area_nome',
            field=models.CharField(default='Piscina', max_length=100),
        ),
        migrations.DeleteModel(
            name='AreaComum',
        ),
    ]
