# Generated by Django 5.1.7 on 2025-05-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0014_remove_reserva_area_reserva_area_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='area_nome',
            field=models.CharField(max_length=100),
        ),
    ]
