# Generated by Django 5.1.7 on 2025-05-10 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0016_visitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(help_text="Classe do ícone do BoxIcons, ex: 'bx bxs-party'", max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-data', '-horario']},
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='data_reserva',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='morador',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condosync.areacomum'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condosync.horario'),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('area', 'data', 'horario')},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='area_nome',
        ),
    ]
