# Generated by Django 5.2 on 2025-05-11 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0017_areacomum_horario_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacomum',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condosync.areacomum'),
        ),
    ]
