# Generated by Django 5.2 on 2025-05-14 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0020_alter_ocorrencia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomendas', to='condosync.apartamento'),
        ),
    ]
