# Generated by Django 5.2 on 2025-05-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0022_alter_reserva_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
