# Generated by Django 5.1.7 on 2025-05-22 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0023_alter_reserva_horario_delete_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condosync.horario'),
        ),
    ]
