# Generated by Django 5.1.7 on 2025-05-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0024_horario_alter_reserva_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-data']},
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('area', 'data')},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='horario',
        ),
    ]
