# Generated by Django 5.1.7 on 2025-05-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condosync', '0026_alter_reserva_options_alter_reserva_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-data']},
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('area', 'data')},
        ),
    ]
